# Generated by Django 3.1.3 on 2020-12-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-count_sold', 'name'), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='count_sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
