# Generated by Django 3.1.3 on 2020-12-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201210_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-count_sold',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
